#!/usr/sbin/nft -f

flush ruleset

table ip nat {
  chain postrouting {
    type nat hook postrouting priority 100;
    oifname "ens18" ip saddr 192.168.10.0/24 masquerade
  }
}

table inet filter {
  chain forward {
    type filter hook forward priority 0;
    policy drop;

    iifname "ens19" oifname "ens18" accept
    iifname "ens18" oifname "ens19" ct state established,related accept
  }
}
